export const projects = [
  {
    title: "KidsCalendar",
    description:
      "Web application for organizing daily tasks between parents and children, with personal dashboards, progress tracking, calendar-based planning, and educational motivation mechanics.",
    role: "Full-stack Developer",
    backend: [
      "User Authentication: Implemented secure parent and child login with JWT-based tokens, stored in Redux state on the frontend.",
      "Password Hashing: Used bcrypt to hash passwords before storing in PostgreSQL.",
      "Role Separation: API logic is split between parent and child flows, with separate endpoints and access validation.",
      "PostgreSQL Integration: Designed and connected relational database models for users, children, task lists, and calendar data.",
      "Secure API Design: Created RESTful API routes for authentication, task management, and user-child associations with token verification middleware.",
      "Dev Tools: Used `dotenv` for environment variables, `cors` for cross-origin requests, and `morgan` for logging.",
    ],
    frontend: [
      "Landing Page with Video Background: Created a responsive landing screen with animated background video and multilingual support (EN/DE/UA/RU).",
      "Separate Dashboards: Built individual views for parents (task creation, control) and children (task list, status updates).",
      "Protected Routes: Integrated access control using React Router for private/public login zones.",
      "Custom UI Components: Built reusable components like calendar task lists, kid selector, and animated feedback blocks.",
    ],
    technologies: [
      "JavaScript",
      "React",
      "HTML",
      "Sass",
      "Redux",
      "Axios",
      "Git",
      "GitHub",
      "Figma",
      "Trello",
      "Node.js",
      "Express",
      "PostgreSQL",
      "Dotenv",
      "VSCode",
      "ESLint",
      "Prettier",
    ],
    liveLink: "https://react-app-self-seven.vercel.app/",
  },
  {
    title: "CHIP TUNING",
    description:
      "Web application for managing and customizing car chip tuning services, including dynamic vehicle filtering, order handling, and performance result visualization",
    role: "Full-stack Developer",
    backend: [
      "Order Management System: Developed a custom order management system with full CRUD operations, status-based filtering, data editing, and the ability to send updates to clients.",
      "Role-Based Access Control: Implemented user role handling (admin, manager) with access restrictions and UI adjustments based on the assigned role.",
      "File Upload & Storage: Enabled file uploads from the client side, integrated with Google Drive API for cloud storage, and handled file ID management and error cases.",
      "Dynamic Vehicle Filter API: Created PHP endpoints to serve dynamic filter data (make, model, engine, etc.), with support for caching and dependent dropdowns.",
      "Custom Service Data: Built a system for selecting, saving, and displaying tuning services using JSON-formatted data to support multi-selection and flexible rendering.",
    ],
    frontend: [
      "Custom Multi-Select UI: Designed a custom multi-select component using checkboxes and dropdown-like behavior to allow selection of multiple tuning services.",
      "Dependent Select Logic: Implemented a chain of dynamic select inputs (Make → Model → Fuel → Engine) with real-time data loading and automatic reset of dependent fields.",
      "Animated Performance Metrics: Created animated visual indicators for BHP and Torque gains, dynamically updated based on user input or tuning selection.",
      "Form Validation & Result Display: Added client-side validation, custom error notifications, and a responsive results block showing tuning outcomes.",
      "Admin Dashboard Interface: Added custom checkboxes for editing selected services in orders and implemented a file upload feature to attach ready-made tuning files to each order.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "Sass",
      "Webpack",
      "PHP",
      "Axios",
      "MySQL",
      "Git",
      "GitHub",
      "Figma",
      "Trello",
      "VSCode",
      "ESLint",
      "Prettier",
    ],
    liveLink: "https://chip-tuning.com.ua/",
  },
  {
    title: "Brovko",
    description:
      "Web application about tasty and healthy goodies for dogs. The platform includes a product catalog, user accounts, shopping cart functionality, and administrative management features. It aims to promote healthy nutrition for pets while providing a smooth shopping experience.",
    role: "Full-stack Developer",
    backend: [
      "User Management: Implemented and managed user-related functionalities, including user registration, login, and profile management.",
      "Authentication: Integrated Google authentication and refresh token mechanisms to enhance security and user experience.",
      "Refactoring: Conducted significant refactoring of backend components, improving code quality and maintainability across controllers, routes, middleware, services, and models.",
      "File Handling: Utilized Multer for file uploads and Sharp for image processing, effectively managing user-uploaded content.",
    ],
    frontend: [
      "User Features: Developed user-centric features such as authentication, cart management, and order history.",
      "Modal Windows: Implemented modal windows to handle user interactions and display dynamic content.",
      "State Management: Refactored Redux store, services, and hooks to optimize state management and improve application performance.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "Sass",
      "Webpack",
      "React",
      "Redux",
      "Axios",
      "Node.js",
      "MongoDB",
      "Cloudinary",
      "Express",
      "Mongoose",
      "Swagger",
      "Git",
      "GitHub",
      "Figma",
      "Trello",
      "VSCode",
      "ESLint",
      "Prettier",
    ],
  },
  {
    title: "Cards for you",
    description:
      "Web application for learning English words using interactive flashcards. Designed for self-study, it supports pre-built and user-generated word lists, interactive card flipping, and local storage to retain progress across sessions.",

    role: "Front-end Developer",
    frontend: [
      "Dynamic Vocabulary Lists: Implemented a system for displaying various English word lists (e.g., irregular verbs, most used words) and switching between them without page reloads.",
      "Flashcard Mechanism: Created interactive, flippable flashcards to enhance the learning experience, including next/previous navigation and front/back text display.",
      "User Inputs and Own Lists: Enabled users to add their own words and translations via a custom input form, persisting data in LocalStorage for offline use and personalized study.",
      "Responsive UI: Utilized Tailwind CSS for a clean, responsive design ensuring a seamless experience across various devices.",
      "LocalStorage Integration: Stored user-generated word lists locally, allowing continuity of learning progress after page reloads.",
      "Computed Properties and Reactivity: Leveraged Vue's reactivity and computed properties to automatically update the UI when switching between lists or modifying the current word index.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "Vue.js",
      "Tailwind",
      "Vite",
      "Git",
      "GitHub",
      "Figma",
      "Trello",
      "VSCode",
      "ESLint",
      "Prettier",
    ],
    liveLink: "https://alexdembno.github.io/cards-for-you/",
    githubLink: "https://github.com/AlexDembno/cards-for-you",
  },
  {
    title: "Law company",
    description:
      "Website for law firm, showcasing services, legal team, and contact options. Built to reflect a professional corporate image, optimize for SEO, and simplify communication between clients and the legal office.",

    role: "Full-stack Developer",
    backend: [
      "Contact Form Integration: Implemented a secure and user-friendly contact form, enabling clients to submit inquiries directly through the website. Configured server-side validation and email notifications using Nodemailer.",
      "Email Notifications: Set up automated email responses to confirm receipt of client inquiries, improving user communication and engagement.",
      "Server Optimization: Built a lightweight and efficient server using Node.js and Express, ensuring quick response times and seamless navigation for users.",
    ],
    frontend: [
      "Responsive Design: Crafted a responsive layout using HTML and SASS, ensuring an optimal viewing experience across devices, including desktops, tablets, and smartphones.",
      "Interactive Elements: Enhanced user experience with dynamic JavaScript features, such as real-time form validation and smooth scrolling to sections.",
      "Styling: Designed a clean and professional user interface tailored to the needs of a legal firm, emphasizing accessibility and readability.",
      "Performance Optimization: Minimized CSS and JS for faster load times, contributing to an improved user experience.",
    ],
    technologies: [
      "HTML",
      "Sass",
      "JavaScript",
      "Node.js",
      "Express",
      "Git",
      "GitHub",
      "Figma",
      "Trello",
      "VSCode",
      "ESLint",
      "Prettier",
    ],
    liveLink:
      "https://law-company-git-main-oleksiis-projects-32951c36.vercel.app/",
    githubLink: "https://github.com/AlexDembno/law-company",
  },
  {
    title: "Your pet",
    description:
      "Patron-4U is a platform for connecting with like-minded pet owners. Users can create tasks, manage pet profiles, and stay informed through notifications. Built to facilitate care coordination among pet communities.",

    role: "Full-stack Developer",
    backend: [
      "Node.js and Express: Created REST API for handling requests and managing data.",
      "Routes and Controllers: Implemented business logic for users, tasks, and notifications with modular structure.",
      "MongoDB: Set up the database for data storage and management, including pet profiles and task tracking.",
      "Authentication: Integrated JWT-based authentication with secure password hashing and token verification.",
      "Data Validation: Used middleware to validate incoming data structures and ensure integrity.",
      "Swagger: Integrated API documentation for backend routes to assist developers during integration and testing.",
    ],

    frontend: [
      "React and Redux Toolkit: Built dynamic interfaces and managed application state across user sessions.",
      "Responsive Dashboard: Created a user dashboard for managing pet profiles, scheduled tasks, and notifications.",
      "UI/UX Design: Implemented a pet-friendly interface using Figma guidelines, ensuring accessibility and simplicity.",
      "Task Manager UI: Developed interactive task list with status updates, filter options, and due dates.",
      "Sass Styling: Used nested SCSS for modular styling and component theming.",
      "Webpack: Optimized the build pipeline to reduce load times and improve performance across devices.",
    ],
    technologies: [
      "HTML",
      "Sass",
      "JavaScript",
      "Webpack",
      "React",
      "Redux",
      "Node.js",
      "MongoDB",
      "Express",
      "Git",
      "Figma",
      "VSCode",
      "Trello",
      "ESLint",
      "Prettier",
      "Swagger",
    ],
    liveLink: "https://patron4u-pet-app.netlify.app/main",
    githubLink: "https://github.com/OlgaVysochanska/project-patron4U",
  },
  {
    title: "Filmoteka",
    description:
      "Collaboratively developed a web application for browsing and managing a film library, using The Movie Database API. Users can search, view movie details, add films to their watched list, and mark favorites.",

    role: "Frontend Developer",
    frontend: [
      "User Interfaces: Developed responsive and dynamic user interfaces with modular structure as part of a team effort.",
      "Movie Catalog: Integrated The Movie Database (TMDb) API to fetch real-time movie data and dynamically display content.",
      "Search & Filters: Implemented keyword search and category filtering to help users discover content.",
      "Loading Indicator & Notifications: Created loading animation and user-friendly error/success notification system.",
      "Favorites & Watched: Enabled users to save and retrieve a list of watched or favorite films using localStorage.",
      "Sass Styling: Designed mobile-first layout using nested SCSS and adaptive breakpoints.",
    ],
    technologies: [
      "HTML",
      "Sass",
      "JavaScript",
      "Handlebars",
      "GitHub",
      "Figma",
      "Trello",
      "VSCode",
      "ESLint",
      "Prettier",
    ],
    liveLink: "https://orddreamer.github.io/filmoteka-first-command/",
    githubLink: "https://github.com/OrdDreamer/filmoteka-first-command",
  },
  {
    title: "Ice cream shop",
    description:
      "Designed and developed a visually appealing section for an ice cream shop website. Focus was on creative layout, engaging color palette, and enhancing user interaction through smooth modals and responsive design.",

    role: "Frontend Developer",
    frontend: [
      "Unique Positioning: Developed a section with unique layout positioning using flex and absolute styles for modern feel.",
      "Modal Window: Created a modal window component for product details and ordering interaction.",
      "Adaptive Layout: Ensured that the section displayed consistently across various screen sizes using media queries.",
      "Animation Effects: Added subtle transitions and hover effects to enhance user experience.",
      "Interactive Elements: Developed simple JavaScript-based interactions to improve product engagement.",
    ],
    technologies: [
      "HTML",
      "Sass",
      "JavaScript",
      "GitHub",
      "Figma",
      "Trello",
      "VSCode",
      "ESLint",
      "Prettier",
    ],
    liveLink: "https://orddreamer.github.io/ice-cream/",
    githubLink: "https://github.com/OrdDreamer/ice-cream",
  },
  {
    title: "WebStudio",
    description:
      "Developed a complete static website from scratch, simulating a modern business homepage. Implemented responsive design, optimized build with Parcel, and used SCSS and JavaScript to enhance interactivity and performance.",
    role: "Frontend Developer",
    frontend: [
      "Static Website: Built the entire website using HTML and SCSS, with a focus on clean structure and BEM methodology.",
      "Dynamic Features: Implemented image slider, mobile menu toggle, and smooth scrolling using vanilla JavaScript.",
      "Build Optimization: Used Parcel for bundling assets, enabling hot reloading and optimized production builds.",
      "Accessibility: Ensured semantic markup and keyboard navigation support for improved user accessibility.",
      "Responsive Grid: Used flexbox and media queries to create responsive service, portfolio, and team sections.",
    ],
    technologies: [
      "HTML",
      "Sass",
      "JavaScript",
      "GitHub",
      "Figma",
      "Trello",
      "VSCode",
      "ESLint",
      "Prettier",
    ],
    liveLink: "https://alexdembno.github.io/goit-markup-hw-08/",
    githubLink: "https://github.com/AlexDembno/goit-markup-hw-08",
  },
];

export default projects;
